import { createContext, useContext, useState, ReactNode } from 'react';

interface LanguageContextType {
  language: 'en' | 'zh';
  setLanguage: (lang: 'en' | 'zh') => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // General
    searchInformation: 'Search Information',
    dataList: 'Data List',
    hotTopics: 'Hot Topics',
    home: 'Home',
    dashboard: 'Dashboard',
    signIn: 'Sign In',
    getStarted: 'Get Started',
    learnMore: 'Learn More',
    search: 'Search',
    query: 'Query',
    faq: 'FAQ',
    footerText: '© 2025 KnowBase. All rights reserved.',
    professionalService: 'Professional Service',
    advancedDatabase: 'Advanced Database',
    querySystem: 'Query System',
    professionalGrade: 'KnowBase Query System',
    powerfulFeatures: 'Powerful Features',
    everythingYouNeed: 'Everything you need for comprehensive data queries.',
    comprehensiveDatabase: 'Comprehensive Database',
    comprehensiveDatabaseDesc: 'Access millions of records with detailed information.',
    lightningFast: 'Lightning Fast',
    lightningFastDesc: 'Optimized for speed with instant query results.',
    secureAccess: 'Secure Access',
    secureAccessDesc: 'Enterprise-grade security with encrypted connections.',
    readyToStart: 'Ready to Start?',
    joinSecurity: 'Join thousands of security professionals using our platform.',
    getInvitationCode: 'Get Invitation Code',
    startResearch: 'Start Research',
    searchPlaceholder: 'Enter email, phone, or name',
    points: 'Points',
    all: 'All',
    otherEnquiries: 'Other Enquiries',
    locationAddress: 'Location & Address',
    propertyRelated: 'Property Related',
    identityRelated: 'Identity Related',
    communicationRelated: 'Communication Related',
    realTimeLocation: 'Real-Time Location',
    personalInfo: 'Personal Info',
    assetsProperty: 'Assets & Property',
    communicationSocial: 'Communication & Social',
    searchResults: 'Search Results',
    found: 'found',
    email: 'Email',
    phone: 'Phone',
    name: 'Name',
    mixed: 'Mixed',
    location: 'Location',
    address: 'Address',
    property: 'Property',
    social: 'Social Media',
    investigateMistress: 'Investigate Potential Infidelity',
    investigateMistressDesc: 'Discreetly gather information with our specialized query services.',
    startInvestigation: 'Start Investigation',
    findDebtCollector: 'Find a Debt Collector',
    findDebtCollectorDesc: 'Locate individuals with our comprehensive database queries.',
    contactService: 'Contact Service',
    databaseSize: 'Database Size',
    records: 'Records',
    uptime: 'Uptime',
    support: 'Support',
    // Services
    phoneOwner: 'Phone Owner',
    phoneOwnerDesc: 'Identify the owner of a phone number.',
    checkPersonalMobile: 'Check Personal Mobile',
    checkPersonalMobileDesc: 'Verify personal mobile details.',
    realTimeLocationAuth: 'Real-Time Location (Authorized)',
    realTimeLocationAuthDesc: 'Track authorized real-time location data.',
    expressDelivery: 'Express Delivery Tracking',
    expressDeliveryDesc: 'Track express delivery in real time.',
    flightSearch: 'Flight Search',
    flightSearchDesc: 'Search flight records and travel history.',
    vehicleTrajectory: 'Vehicle Trajectory',
    vehicleTrajectoryDesc: 'Track vehicle movement history.',
    flightTrainTravel: 'Flight & Train Travel',
    flightTrainTravelDesc: 'Query flight and train travel records.',
    personalPolicy: 'Personal Policy',
    personalPolicyDesc: 'Access personal policy information.',
    comprehensiveQuery: 'Comprehensive Query',
    comprehensiveQueryDesc: 'Full spectrum data query service.',
    householdRegistration: 'Household Registration',
    householdRegistrationDesc: 'Query household registration details.',
    fullHouseholdRegistration: 'Full Household Registration',
    fullHouseholdRegistrationDesc: 'Detailed household registration data.',
    marriageRecord: 'Marriage Record',
    marriageRecordDesc: 'Access marriage records.',
    companyShareholder: 'Company Shareholder',
    companyShareholderDesc: 'Identify company shareholders.',
    educationInfo: 'Education Info',
    educationInfoDesc: 'Query educational background.',
    backgroundQuery: 'Background Query',
    backgroundQueryDesc: 'Comprehensive background check.',
    workUnit: 'Work Unit',
    workUnitDesc: 'Query workplace information.',
    addressQuery: 'Address Query',
    addressQueryDesc: 'Find address details.',
    passportEnquiry: 'Passport Enquiry',
    passportEnquiryDesc: 'Query passport information.',
    allProperties: 'All Properties',
    allPropertiesDesc: 'Query all property ownership.',
    vehicleInfo: 'Vehicle Info',
    vehicleInfoDesc: 'Access vehicle ownership details.',
    vehicleFileQuery: 'Vehicle File Query',
    vehicleFileQueryDesc: 'Detailed vehicle file information.',
    bankCheck: 'Bank Check',
    bankCheckDesc: 'Verify bank account details.',
    bankTransaction: 'Bank Transaction',
    bankTransactionDesc: 'Query bank transaction history.',
    alipayAccount: 'Alipay Account',
    alipayAccountDesc: 'Query Alipay account details.',
    transactionCheck: 'Transaction Check',
    transactionCheckDesc: 'Verify transaction history.',
    loanInfo: 'Loan Info',
    loanInfoDesc: 'Query loan information.',
    allPersonalProperty: 'All Personal Property',
    allPersonalPropertyDesc: 'Comprehensive personal property query.',
    criminalSearch: 'Criminal Search',
    criminalSearchDesc: 'Search criminal records.',
    wechatContent: 'WeChat Content',
    wechatContentDesc: 'Query WeChat communication data.',
    freezingReason: 'Freezing Reason',
    freezingReasonDesc: 'Identify reasons for account freezing.',
    wechatCancellation: 'WeChat Cancellation',
    wechatCancellationDesc: 'Query WeChat account cancellation.',
    alipayMobile: 'Alipay Mobile',
    alipayMobileDesc: 'Query Alipay mobile details.',
    realNameInfo: 'Real Name Info',
    realNameInfoDesc: 'Verify real name information.',
    threeNetworkMobile: 'Three Network Mobile',
    threeNetworkMobileDesc: 'Query mobile data across three networks.',
    wechatRecovery: 'WeChat Recovery',
    wechatRecoveryDesc: 'Assist with WeChat account recovery.',
    qqFriendCollection: 'QQ Friend Collection',
    qqFriendCollectionDesc: 'Query QQ friend connections.',
    generalInfo: 'General Info',
    generalInfoDesc: 'General information query.',
    documentVerification: 'Document Verification',
    documentVerificationDesc: 'Verify document authenticity.',
    identityConfirmation: 'Identity Confirmation',
    identityConfirmationDesc: 'Confirm identity details.',
    backgroundScreening: 'Background Screening',
    backgroundScreeningDesc: 'Perform background screening.',
    contactVerification: 'Contact Verification',
    contactVerificationDesc: 'Verify contact information.',
    // FAQ
    faqQuestion1: 'What is a social engineering database query system?',
    faqAnswer1: 'A social engineering database query system is a tool used by cybersecurity professionals to search for publicly available information that might be used in social engineering attacks. It helps identify potential security vulnerabilities and educate users about privacy risks.',
    faqQuestion2: 'How do I earn points to use the system?',
    faqAnswer2: 'You can earn points by purchasing them through our USDT payment system, or by receiving invitation rewards when you successfully invite new users to the platform.',
    faqQuestion3: 'What types of information can I search for?',
    faqAnswer3: 'Our system allows you to search for various types of publicly available information including email addresses, phone numbers, usernames, and associated data from public breaches and leaks.',
    faqQuestion4: 'Is this system legal to use?',
    faqAnswer4: 'Yes, our system only provides access to publicly available information and is intended for legitimate cybersecurity research, penetration testing, and educational purposes. Users must comply with local laws and regulations.',
    faqQuestion5: 'How much do queries cost?',
    faqAnswer5: 'Query costs vary depending on the type and complexity of the search. Basic queries typically cost 1-5 points, while comprehensive searches may cost 10-20 points.',
    faqQuestion6: 'Can I export my search results?',
    faqAnswer6: 'Yes, VIP users can export their search results in various formats including CSV and JSON for further analysis and reporting.',
    faqQuestion7: 'What is the invitation system?',
    faqAnswer7: 'Our invitation system allows existing users to invite new members to the platform. Both the inviter and invitee receive bonus points when the invitation is successfully used.',
    faqQuestion8: 'How secure is my data on this platform?',
    faqAnswer8: 'We implement industry-standard security measures including encryption, secure authentication, and regular security audits to protect user data and queries.',
    faqQuestion9: 'What payment methods do you accept?',
    faqAnswer9: 'We currently accept USDT (Tether) payments for purchasing points. This ensures fast, secure, and anonymous transactions.',
    faqQuestion10: 'Can I use the API for automated queries?',
    faqAnswer10: 'Yes, VIP users have access to our API endpoints for automated querying. API access requires special permissions and additional security verification.',
    // Bulletin Board
    bulletinBoard: 'Bulletin Board',
    announcement1: 'New Feature Release!',
    announcement1Content: 'We have added advanced search filters and export options for VIP users.',
    announcement2: 'System Maintenance',
    announcement2Content: 'Scheduled maintenance on May 30, 2025, from 2 AM to 4 AM UTC.',
    announcement3: 'VIP Discount Offer',
    announcement3Content: 'Get 20% off on VIP Pack purchases until June 1, 2025!',
    // Ad Carousel
    ad1Title: 'Upgrade to VIP',
    ad1Content: 'Unlock advanced search features and export options with our VIP plan!',
    ad1CTA: 'Learn More',
    ad2Title: 'Invite Friends',
    ad2Content: 'Earn bonus points by inviting your friends to join KnowBase.',
    ad2CTA: 'Invite Now',
    ad3Title: 'Secure Your Data',
    ad3Content: 'Our platform uses industry-leading encryption to protect your searches.',
    ad3CTA: 'Explore Security'
  },
  zh: {
    // General
    searchInformation: '搜索信息',
    dataList: '数据列表',
    hotTopics: '热门话题',
    home: '首页',
    dashboard: '仪表板',
    signIn: '登录',
    getStarted: '开始使用',
    learnMore: '了解更多',
    search: '搜索',
    query: '查询',
    faq: '常见问题',
    footerText: '© 2025 KnowBase。保留所有权利。',
    professionalService: '专业服务',
    advancedDatabase: '高级数据库',
    querySystem: '查询系统',
    professionalGrade: '为安全研究人员和分析师提供专业级数据库查询系统。',
    powerfulFeatures: '强大功能',
    everythingYouNeed: '满足您全面数据查询所需的一切。',
    comprehensiveDatabase: '全面数据库',
    comprehensiveDatabaseDesc: '访问数百万条详细信息的记录。',
    lightningFast: '闪电般快速',
    lightningFastDesc: '优化速度，即时查询结果。',
    secureAccess: '安全访问',
    secureAccessDesc: '企业级安全，加密连接。',
    readyToStart: '准备开始？',
    joinSecurity: '加入数千名使用我们平台的安全专业人员。',
    getInvitationCode: '获取邀请码',
    startResearch: '开始研究',
    searchPlaceholder: '输入邮箱、电话或姓名',
    points: '积分',
    all: '全部',
    otherEnquiries: '其他查询',
    locationAddress: '位置与地址',
    propertyRelated: '财产相关',
    identityRelated: '身份相关',
    communicationRelated: '通信相关',
    realTimeLocation: '实时位置',
    personalInfo: '个人信息',
    assetsProperty: '资产与财产',
    communicationSocial: '通信与社交',
    searchResults: '搜索结果',
    found: '找到',
    email: '邮箱',
    phone: '电话',
    name: '姓名',
    mixed: '混合',
    location: '位置',
    address: '地址',
    property: '财产',
    social: '社交媒体',
    investigateMistress: '调查潜在不忠',
    investigateMistressDesc: '使用我们的专业查询服务谨慎收集信息。',
    startInvestigation: '开始调查',
    findDebtCollector: '寻找债务人',
    findDebtCollectorDesc: '使用我们全面的数据库查询定位个人。',
    contactService: '联系服务',
    databaseSize: '数据库规模',
    records: '记录',
    uptime: '正常运行时间',
    support: '支持',
    // Services
    phoneOwner: '电话拥有者',
    phoneOwnerDesc: '识别电话号码的拥有者。',
    checkPersonalMobile: '检查个人手机',
    checkPersonalMobileDesc: '验证个人手机详情。',
    realTimeLocationAuth: '实时位置（授权）',
    realTimeLocationAuthDesc: '跟踪授权的实时位置数据。',
    expressDelivery: '快递跟踪',
    expressDeliveryDesc: '实时跟踪快递。',
    flightSearch: '航班搜索',
    flightSearchDesc: '搜索航班记录和旅行历史。',
    vehicleTrajectory: '车辆轨迹',
    vehicleTrajectoryDesc: '跟踪车辆移动历史。',
    flightTrainTravel: '航班与火车旅行',
    flightTrainTravelDesc: '查询航班和火车旅行记录。',
    personalPolicy: '个人保单',
    personalPolicyDesc: '访问个人保单信息。',
    comprehensiveQuery: '综合查询',
    comprehensiveQueryDesc: '全谱数据查询服务。',
    householdRegistration: '户籍登记',
    householdRegistrationDesc: '查询户籍登记详情。',
    fullHouseholdRegistration: '完整户籍登记',
    fullHouseholdRegistrationDesc: '详细的户籍登记数据。',
    marriageRecord: '婚姻记录',
    marriageRecordDesc: '访问婚姻记录。',
    companyShareholder: '公司股东',
    companyShareholderDesc: '识别公司股东。',
    educationInfo: '教育信息',
    educationInfoDesc: '查询教育背景。',
    backgroundQuery: '背景查询',
    backgroundQueryDesc: '全面背景检查。',
    workUnit: '工作单位',
    workUnitDesc: '查询工作单位信息。',
    addressQuery: '地址查询',
    addressQueryDesc: '查找地址详情。',
    passportEnquiry: '护照查询',
    passportEnquiryDesc: '查询护照信息。',
    allProperties: '所有物业',
    allPropertiesDesc: '查询所有物业所有权。',
    vehicleInfo: '车辆信息',
    vehicleInfoDesc: '访问车辆所有权详情。',
    vehicleFileQuery: '车辆档案查询',
    vehicleFileQueryDesc: '详细的车辆档案信息。',
    bankCheck: '银行检查',
    bankCheckDesc: '验证银行账户详情。',
    bankTransaction: '银行交易',
    bankTransactionDesc: '查询银行交易历史。',
    alipayAccount: '支付宝账户',
    alipayAccountDesc: '查询支付宝账户详情。',
    transactionCheck: '交易检查',
    transactionCheckDesc: '验证交易历史。',
    loanInfo: '贷款信息',
    loanInfoDesc: '查询贷款信息。',
    allPersonalProperty: '所有个人财产',
    allPersonalPropertyDesc: '全面的个人财产查询。',
    criminalSearch: '犯罪搜索',
    criminalSearchDesc: '搜索犯罪记录。',
    wechatContent: '微信内容',
    wechatContentDesc: '查询微信通信数据。',
    freezingReason: '冻结原因',
    freezingReasonDesc: '识别账户冻结原因。',
    wechatCancellation: '微信注销',
    wechatCancellationDesc: '查询微信账户注销。',
    alipayMobile: '支付宝手机',
    alipayMobileDesc: '查询支付宝手机详情。',
    realNameInfo: '实名信息',
    realNameInfoDesc: '验证实名信息。',
    threeNetworkMobile: '三大网络手机',
    threeNetworkMobileDesc: '查询三大网络的手机数据。',
    wechatRecovery: '微信恢复',
    wechatRecoveryDesc: '协助微信账户恢复。',
    qqFriendCollection: 'QQ好友收集',
    qqFriendCollectionDesc: '查询QQ好友连接。',
    generalInfo: '常规信息',
    generalInfoDesc: '常规信息查询。',
    documentVerification: '文件验证',
    documentVerificationDesc: '验证文件真实性。',
    identityConfirmation: '身份确认',
    identityConfirmationDesc: '确认身份详情。',
    backgroundScreening: '背景筛选',
    backgroundScreeningDesc: '进行背景筛选。',
    contactVerification: '联系方式验证',
    contactVerificationDesc: '验证联系信息。',
    // FAQ
    faqQuestion1: '什么是社会工程数据库查询系统？',
    faqAnswer1: '社会工程数据库查询系统是网络安全专业人员使用的工具，用于搜索可能在社会工程攻击中使用的公开信息。它有助于识别潜在的安全漏洞并教育用户了解隐私风险。',
    faqQuestion2: '如何获得使用系统的积分？',
    faqAnswer2: '您可以通过我们的USDT支付系统购买积分，或在成功邀请新用户加入平台时获得邀请奖励积分。',
    faqQuestion3: '我可以搜索哪些类型的信息？',
    faqAnswer3: '我们的系统允许您搜索各种公开信息，包括电子邮件地址、电话号码、用户名以及来自公共泄露和泄漏的关联数据。',
    faqQuestion4: '使用此系统合法吗？',
    faqAnswer4: '是的，我们的系统仅提供对公开信息的访问，旨在用于合法的网络安全研究、渗透测试和教育目的。用户必须遵守当地法律法规。',
    faqQuestion5: '查询费用是多少？',
    faqAnswer5: '查询费用根据搜索类型和复杂程度而异。基本查询通常需要1-5积分，而综合搜索可能需要10-20积分。',
    faqQuestion6: '我可以导出搜索结果吗？',
    faqAnswer6: '是的，VIP用户可以将搜索结果导出为CSV和JSON等格式，以便进一步分析和报告。',
    faqQuestion7: '什么是邀请系统？',
    faqAnswer7: '我们的邀请系统允许现有用户邀请新成员加入平台。邀请者和被邀请者在邀请成功使用时均可获得奖励积分。',
    faqQuestion8: '平台上的数据安全性如何？',
    faqAnswer8: '我们实施了行业标准的安全措施，包括加密、安全认证和定期安全审计，以保护用户数据和查询。',
    faqQuestion9: '你们接受哪些支付方式？',
    faqAnswer9: '我们目前接受USDT（Tether）支付购买积分。这确保了快速、安全和匿名的交易。',
    faqQuestion10: '我可以使用API进行自动查询吗？',
    faqAnswer10: '是的，VIP用户可以访问我们的API端点进行自动查询。API访问需要特殊权限和额外的安全验证。',
    // Bulletin Board
    bulletinBoard: '公告板',
    announcement1: '新功能发布！',
    announcement1Content: '我们为VIP用户添加了高级搜索过滤器和导出选项。',
    announcement2: '系统维护',
    announcement2Content: '2025年5月30日凌晨2点至4点（UTC）进行计划维护。',
    announcement3: 'VIP折扣优惠',
    announcement3Content: '截至2025年6月1日，VIP套餐购买可享20%折扣！',
    // Ad Carousel
    ad1Title: '升级到VIP',
    ad1Content: '通过我们的VIP计划解锁高级搜索功能和导出选项！',
    ad1CTA: '了解更多',
    ad2Title: '邀请朋友',
    ad2Content: '通过邀请您的朋友加入KnowBase赚取奖励积分。',
    ad2CTA: '立即邀请',
    ad3Title: '保护您的数据',
    ad3Content: '我们的平台使用行业领先的加密技术保护您的搜索。',
    ad3CTA: '探索安全性'
  }
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<'en' | 'zh'>('en');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};